/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { FooterComponent, HeaderComponent } from "components/modules";
import {
  Testimoni,
  OurMap,
  Partner,
  Favorite,
  Teamwork,
  Hero,
} from "components/molecules";

export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee Brings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeaderComponent />
      <Hero />
      <Teamwork />
      <Favorite />
      <Partner />
      <OurMap />
      <Testimoni />
      <FooterComponent />
    </>
  );
}
